# config/gateway.config.yml

# http
http:
  port: 8080

# apiEndpoints
apiEndpoints:
  users:
    host: localhost
    paths: "/v1/user/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

  ride:
    host: localhost
    paths: "/v1/ride/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

# serviceEndpoints
serviceEndpoints:
  userService:
    url: "http://localhost:3000/"

  rideService:
    url: "http://localhost:4000/"

# policies
policies:
  - cors
  - log
  - jwt
  - proxy

# pipelines
pipelines:
  userPipeline:
    apiEndpoints:
      - users
    policies:
      - cors:x
          - action:
              origin: '*'
              methods: 'GET,PUT,PATCH,POST,DELETE'
      - log:
          - action: 
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  
  ridePipeline:
    apiEndpoints:
      - ride
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET,PUT,PATCH,POST,DELETE'
      # - jwt:
      #     - action:
      #         secretOrPublicKey: 'nodeTypescript'
      #         checkCredentialExistence: false
      - log:
          - action: 
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: rideService
              changeOrigin: true
